# Generated by Django 4.2.7 on 2024-07-27 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bm_bmi',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bm_breakfast',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bm_daily_wakeup_sleep_time',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bm_dinner',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bm_exercise',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bm_job_profile',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bm_lunch',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bm_office',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bm_subject_details',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bm_total_calories',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bm_weight',
            name='date',
        ),
    ]
