# Generated by Django 4.2.7 on 2024-11-08 12:01

from django.db import migrations, models
import djangoapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_rename_person_name_bm_person_info_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bm_bmi',
            name='date',
            field=models.DateField(default=djangoapp.models.get_current_date),
        ),
        migrations.AlterField(
            model_name='bm_breakfast',
            name='date',
            field=models.DateField(default=djangoapp.models.get_current_date),
        ),
        migrations.AlterField(
            model_name='bm_dinner',
            name='date',
            field=models.DateField(default=djangoapp.models.get_current_date),
        ),
        migrations.AlterField(
            model_name='bm_exercise',
            name='date',
            field=models.DateField(default=djangoapp.models.get_current_date),
        ),
        migrations.AlterField(
            model_name='bm_job_profile',
            name='date',
            field=models.DateField(default=djangoapp.models.get_current_date),
        ),
        migrations.AlterField(
            model_name='bm_lunch',
            name='date',
            field=models.DateField(default=djangoapp.models.get_current_date),
        ),
        migrations.AlterField(
            model_name='bm_office',
            name='date',
            field=models.DateField(default=djangoapp.models.get_current_date),
        ),
        migrations.AlterField(
            model_name='bm_subject_details',
            name='date',
            field=models.DateField(default=djangoapp.models.get_current_date),
        ),
        migrations.AlterField(
            model_name='bm_weight',
            name='date',
            field=models.DateField(default=djangoapp.models.get_current_date),
        ),
    ]
