# Generated by Django 4.2.7 on 2024-07-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_remove_bm_bmi_date_remove_bm_breakfast_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bm_bmi',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bm_breakfast',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bm_daily_wakeup_sleep_time',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bm_dinner',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bm_exercise',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bm_job_profile',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bm_lunch',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bm_office',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bm_subject_details',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bm_total_calories',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bm_weight',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
