# Generated by Django 4.2.7 on 2024-12-12 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangoapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djangoapp', '0003_alter_bm_bmi_date_alter_bm_breakfast_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='access_module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='apiresource_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='dashboard_menu_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='depart_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=70)),
                ('is_viewable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='desig_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=70)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmailAccessPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp-mail.outlook.com', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_user', models.EmailField(max_length=254)),
                ('smtp_password', models.CharField(max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='employee_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=15)),
                ('first_name', models.CharField(default='', max_length=70)),
                ('last_name', models.CharField(max_length=70, null=True)),
                ('dateof_joining', models.DateField(default=djangoapp.models.get_current_date)),
                ('phone', models.BigIntegerField(null=True)),
                ('emailaddress', models.CharField(default='', max_length=70)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=djangoapp.models.get_current_dt)),
                ('action', models.CharField(default='Insert', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('auth_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.depart_config')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.desig_config')),
            ],
        ),
        migrations.CreateModel(
            name='forgot_password_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('otp', models.CharField(max_length=100, null=True)),
                ('created_on', models.DateTimeField(default=djangoapp.models.get_current_dt)),
            ],
        ),
        migrations.CreateModel(
            name='InterlockAccessPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='module_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='otp_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.BigIntegerField(default=0, null=True)),
                ('otp', models.BigIntegerField()),
                ('generated_at', models.DateTimeField(null=True)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('role_type', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='role_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='trac_location_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='trac_rework_access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='user_fcm_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(max_length=1000)),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='role_group_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.depart_config')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.role_group')),
                ('role', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.role')),
            ],
        ),
        migrations.CreateModel(
            name='module_access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_access', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.module_config')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='employee_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.employee_config')),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.role')),
            ],
        ),
        migrations.AddField(
            model_name='employee_config',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoapp.trac_location_details'),
        ),
        migrations.CreateModel(
            name='duplicate_access_module_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name_id', models.CharField(max_length=100)),
                ('create_access', models.BooleanField(default=False)),
                ('read_access', models.BooleanField(default=False)),
                ('update_access', models.BooleanField(default=False)),
                ('delete_access', models.BooleanField(default=False)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.role')),
            ],
        ),
        migrations.CreateModel(
            name='dashboard_menu_grouppermission_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.desig_config')),
                ('menu_grouppermission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.dashboard_menu_config')),
            ],
        ),
        migrations.CreateModel(
            name='customer_details_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='', max_length=70)),
                ('phone', models.BigIntegerField(default=False)),
                ('emailaddress', models.CharField(default='', max_length=70)),
                ('database_access', models.CharField(default='', max_length=70)),
                ('module_access', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.module_config')),
            ],
        ),
        migrations.CreateModel(
            name='apiresource_grouppermission_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.apiresource_config')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoapp.desig_config')),
            ],
        ),
        migrations.CreateModel(
            name='api_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_endpoint', models.CharField(blank=True, max_length=300, null=True)),
                ('api_type', models.CharField(blank=True, max_length=250, null=True)),
                ('create_access', models.BooleanField(default=False)),
                ('read_access', models.BooleanField(default=False)),
                ('update_access', models.BooleanField(default=False)),
                ('delete_access', models.BooleanField(default=False)),
                ('module_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.access_module')),
            ],
        ),
        migrations.CreateModel(
            name='access_module_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_access', models.BooleanField(default=False)),
                ('read_access', models.BooleanField(default=False)),
                ('update_access', models.BooleanField(default=False)),
                ('delete_access', models.BooleanField(default=False)),
                ('module_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.access_module')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.role')),
            ],
        ),
    ]
