# Generated by Django 4.2.7 on 2024-07-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_bm_bmi_date_bm_breakfast_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bm_date',
        ),
    ]
