from django.urls import *
from djangoapp.views import *
from djangoapp.view.user_details_view import *
from djangoapp.view.meal_details_view import *
from djangoapp.view.exercise_details_view import *
from djangoapp.view.bmi_details_view import *
from djangoapp.view.subject_details_view import *
from djangoapp.view.office_work_details import *
from djangoapp.view.job_profile import *
from djangoapp.view.add_user_emp_view import *
from djangoapp.view.forgot_password_view import *
from djangoapp.view.email_config_views import *
from djangoapp.view.all_configurations_view import *
from djangoapp.view.access_management import *
from djangoapp.view.user_profile import *
from djangoapp.view.email_config_views import *
from djangoapp.view.location_details_view import *